# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: backstage
#   description: |
#     Backstage is an open-source developer portal that puts the developer experience first.
#   links:
#     - title: Website
#       url: http://backstage.io
#     - title: Documentation
#       url: https://backstage.io/docs
#     - title: Storybook
#       url: https://backstage.io/storybook
#     - title: Discord Chat
#       url: https://discord.com/invite/EBHEGzX
#   annotations:
#     github.com/project-slug: backstage/backstage
#     lighthouse.com/website-url: https://backstage.io
# spec:
#   type: library
#   owner: CNCF
#   lifecycle: experimental

---

###############################
# SYSTEMS
###############################
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: red-hat-developer-hub
  description: "Red Hat Developer Hub is a place where developers can create, share, discover, and manage your organization's code. Based on Spotify Backstage."
  tags:
    - backstage
    - developer
    - hub
    - redhat
  links:
    - url: https://youtu.be/LB1w8hjBt5k?si=2LxmEtIxIyAKcHx6
      title: Red Hat Developer Hub Overview
      type: video
      icon: YouTube
    - url: https://developers.redhat.com/rhdh/overview
      title: Red Hat Developer Hub Homepage
      type: website
      icon: WebAsset
  annotations:
    backstage.io/techdocs-ref: dir:.
spec: 
  owner: user:user
  lifecycle: production
  profile:
    displayName: Red Hat Developer Hub

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests

---
#######################################
# COMPONENTS
#######################################

# QUAY
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quay
  annotations:
    quay.io/repository-slug: 'rhdh-community/rhdh'
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
---
# REDHAT ARGOCD
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redhat-argocd
  annotations:
    argocd/app-selector: 'app=backstage'
    argocd/instance-name: default
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
---
# TEKTON
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tekton
  annotations:
    tekton.dev/cicd: 'true'
    backstage.io/kubernetes-id: 'rhtap'
    backstage.io/kubernetes-namespace: 'tekton-pipelines'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
# JENKINS
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins
  annotations:
    jenkins.io/job-full-name: 'backstage/tssc-sample-sbom-scans'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
