apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-index-json
spec:
  params:
    - name: IMAGE_URL
      type: string
      description: The URL of the image to extract index.json from
    - name: IMAGE_DIGEST
      type: string
      description: The digest of the image
  steps:
    - name: extract-index-json
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/bin/bash
        set -e

        TEST_IMAGE=quay.io/redhat-user-workloads/rhtap-shared-team-tenant/rhtap-backstage-plugins:on-pr-969d69a71f6f903bd16171b4d46330242f7b4a0d@sha256:df89d0bd76b606add3c419838e64c6c58d76448807b96ff70f59e2e66698c530
        # Install tools
        echo "Installing tools..."
        microdnf install -y tar findutils curl jq gzip

        # Create directory for extracted files
        mkdir -p /tmp/extracted

        # Install Oras
        echo "Installing ORAS..."
        # Docs: https://oras.land/docs/installation
        VERSION="1.2.2"
        curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
        mkdir -p oras-install/
        tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
        mv oras-install/oras /usr/local/bin/
        rm -rf oras_${VERSION}_*.tar.gz oras-install/
       
        # Pull the image using ORAS
        echo "Pulling blobs with ORAS..."
        # Christophe's WIP image
        oras blob fetch "$TEST_IMAGE" -o layers.tar.gz
        echo "Eventually will be: oras blob fetch $(params.IMAGE_URL)@$(params.IMAGE_DIGEST) -o layers.tar.gz"

        # Extract the files
        mkdir artifact-contents && tar -xvf layers.tar.gz -C artifact-contents

        # Find all index.json files
        find artifact-contents -name "index.json" -type f | tee /tmp/found_files.txt

        if [ -s /tmp/found_files.txt ]; then
          INDEX_PATH=$(head -1 /tmp/found_files.txt)
          echo "Found index.json at: $INDEX_PATH"
          cp "$INDEX_PATH" /tmp/extracted/index.json
          echo "Contents of index.json:"
          cat /tmp/extracted/index.json | jq
          echo "B64 Encoding:"
          BASE64_HASH=$(base64 -w 0 /tmp/extracted/index.json)
          echo "$BASE64_HASH"
        else
          echo "Could not find index.json in the container"
          exit 1
        fi

        echo "Extracting original manifest..."
        oras manifest "$TEST_IMAGE" | jq > manifest.json

        # Add annotation
        echo "Adding annotation..."
        BASE64_HASH=$(base64 -w 0 /tmp/extracted/index.json)
        jq --arg hash "$BASE64_HASH" '.annotations += {"io.backstage.dynamic-packages": $hash}' manifest.json > updated-manifest.json

        # Debug log
        echo "Updated manifest:"
        cat updated-manifest.json | jq

        # Attempt to push the new manifest
        echo "Attempting push..."
        oras manifest push "$TEST_IMAGE" updated-manifest.json && echo "Push Succeeded!"
