apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-index-json
spec:
  params:
    - name: IMAGE_URL
      type: string
      description: The URL of the image to extract index.json from
    - name: IMAGE_DIGEST
      type: string
      description: The digest of the image
  steps:
    - name: extract-index-json
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/bin/bash
        set -e

        # Install tools
        echo "Installing tools..."
        microdnf install -y tar findutils curl jq gzip

        # Create directory for extracted files
        mkdir -p /tmp/extracted

        # Install Oras
        echo "Installing ORAS..."
        # Docs: https://oras.land/docs/installation
        VERSION="1.2.2"
        curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
        mkdir -p oras-install/
        tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
        mv oras-install/oras /usr/local/bin/
        rm -rf oras_${VERSION}_*.tar.gz oras-install/
       
        # Pull the image using ORAS
        echo "Pulling blobs with ORAS..."
        oras blob fetch $(params.IMAGE_URL)@$(params.IMAGE_DIGEST) -o layer.tar.gz

        # Extract the files
        mkdir artifact-contents && tar -xvf layer.tar.gz -C artifact-contents

        # Find all index.json files
        find artifact-contents -name "index.json" -type f | tee /tmp/found_files.txt

        if [ -s /tmp/found_files.txt ]; then
          INDEX_PATH=$(head -1 /tmp/found_files.txt)
          echo "Found index.json at: $INDEX_PATH"
          cp "$INDEX_PATH" /tmp/extracted/index.json
          echo "Contents of index.json:"
          cat /tmp/extracted/index.json
          echo "B64 Encoding:"
          BASE64_HASH=$(base64 -w 0 /tmp/extracted/index.json)
          echo "$BASE64_HASH"
        else
          echo "Could not find index.json in the container"
          exit 1
        fi
