apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: output-text
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!bin/sh
        echo "This is a demo task"
